import express from "express";
import { addBoss, addOrganizer, createNewBadge, createCategory, createTournament, verifyToken, getUsers, getOrganizers, getBosses, grantGems, grantCredits, getAdventures, getTournaments, getCategories, getBadges, addCategoryQualification, removeCategoryQualification, listKyc, kycDownloadUrl, getTickets, resolveTicket, uploadBadgeIconRoute, uploadCategoryIconRoute, uploadThemeIconRoute, getThemes, listPendingSignups, getPendingSignupKyc, pendingSignupKycDownloadUrl, approveSignup, rejectSignup } from "../controllers/moderatorController.js";
import { authSuperToken } from "../middlewares/auth.js";
import { generateSignupLink } from "../controllers/authController.js";

const router = express.Router();

router.post("/verify-token", authSuperToken, verifyToken);
router.post("/users", authSuperToken, getUsers);
router.post("/organizers", authSuperToken, getOrganizers);
router.post("/bosses", authSuperToken, getBosses);
router.post("/grant-gems", authSuperToken, grantGems);
router.post("/grant-credits", authSuperToken, grantCredits);
router.post("/adventures", authSuperToken, getAdventures);
router.post("/tournaments", authSuperToken, getTournaments);
router.post("/categories", authSuperToken, getCategories);
router.post("/badges", authSuperToken, getBadges);
router.post("/add-category-qualification", authSuperToken, addCategoryQualification);
router.post("/remove-category-qualification", authSuperToken, removeCategoryQualification);
router.post("/add-boss", authSuperToken, addBoss);
router.post("/add-organizer", authSuperToken, addOrganizer);
router.post("/create-badge", authSuperToken, createNewBadge);
router.post("/create-category", authSuperToken, createCategory);
router.post("/create-tournament", authSuperToken, createTournament);
router.post("/generate-signup-link", authSuperToken, generateSignupLink);
router.post("/list-kyc", authSuperToken, listKyc);
router.post("/kyc-download-url", authSuperToken, kycDownloadUrl);
router.post("/tickets", authSuperToken, getTickets);
router.post("/resolve-ticket", authSuperToken, resolveTicket);
router.post("/upload-badge-icon", authSuperToken, uploadBadgeIconRoute);
router.post("/upload-category-icon", authSuperToken, uploadCategoryIconRoute);
router.post("/upload-theme-icon", authSuperToken, uploadThemeIconRoute);
router.post("/themes", authSuperToken, getThemes);
router.post("/pending-signups", authSuperToken, listPendingSignups);
router.post("/pending-signup-kyc", authSuperToken, getPendingSignupKyc);
router.post("/pending-signup-kyc-download-url", authSuperToken, pendingSignupKycDownloadUrl);
router.post("/approve-signup", authSuperToken, approveSignup);
router.post("/reject-signup", authSuperToken, rejectSignup);

export default router;
